name: Run Tests

on:
  workflow_run:
    workflows: ["Publish Docker image"]
    branches: [main]
    types:
      - completed

jobs:
  run_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run:
          docker run ghcr.io/pablomillancb/denden6:main
