name: Run Tests

on:
  workflow_run:
    workflows: ["Publish Docker image"]
    branches: [main]
    types:
      - completed

jobs:
  run_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./compose.yaml"
          down-flags: "--volumes"
          compose-flags: "logs"
          services: |
            test